name: Document Release

#on:
#  push:
    tags:
      - 'docus-release-*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Find and upload documents
      run: |
        # Upload each .tar.xz as a release asset
        find ready-docus -name '*.tar.xz' | while read -r tar_file; do
          echo "Uploading $tar_file to release..."
          gh release upload $GITHUB_REF_NAME "$tar_file" --clobber
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
